# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from genesis_msgs/LaneReport.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import std_msgs.msg

class LaneReport(genpy.Message):
  _md5sum = "38b4f1a74aa95aed2e054915f544383c"
  _type = "genesis_msgs/LaneReport"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

time stampA					# timestamp for the "A"-part of the message; same as header.stamp
time stampB					# timestamp for the "B"-part of the message

# Lane polynomial in vehicle frame is y = a0 + a1 x + a2 x^2 + a3 x^3
float32 a0
float32 a1
float32 a2
float32 a3

# Mark types: 6 "Invalid" 5 "Botts'Dots" 4 "DoubleLaneMark" 3 "RoadEdge" 2 "Undecided" 1 "Solid" 0 "Dashed" ;
int32 lane_mark_type
# Quality types: 0, 1 "Low Quality" 2, 3 "High Quality"
int32 lane_mark_quality

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','stampA','stampB','a0','a1','a2','a3','lane_mark_type','lane_mark_quality']
  _slot_types = ['std_msgs/Header','time','time','float32','float32','float32','float32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,stampA,stampB,a0,a1,a2,a3,lane_mark_type,lane_mark_quality

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LaneReport, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.stampA is None:
        self.stampA = genpy.Time()
      if self.stampB is None:
        self.stampB = genpy.Time()
      if self.a0 is None:
        self.a0 = 0.
      if self.a1 is None:
        self.a1 = 0.
      if self.a2 is None:
        self.a2 = 0.
      if self.a3 is None:
        self.a3 = 0.
      if self.lane_mark_type is None:
        self.lane_mark_type = 0
      if self.lane_mark_quality is None:
        self.lane_mark_quality = 0
    else:
      self.header = std_msgs.msg.Header()
      self.stampA = genpy.Time()
      self.stampB = genpy.Time()
      self.a0 = 0.
      self.a1 = 0.
      self.a2 = 0.
      self.a3 = 0.
      self.lane_mark_type = 0
      self.lane_mark_quality = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4I4f2i().pack(_x.stampA.secs, _x.stampA.nsecs, _x.stampB.secs, _x.stampB.nsecs, _x.a0, _x.a1, _x.a2, _x.a3, _x.lane_mark_type, _x.lane_mark_quality))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.stampA is None:
        self.stampA = genpy.Time()
      if self.stampB is None:
        self.stampB = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.stampA.secs, _x.stampA.nsecs, _x.stampB.secs, _x.stampB.nsecs, _x.a0, _x.a1, _x.a2, _x.a3, _x.lane_mark_type, _x.lane_mark_quality,) = _get_struct_4I4f2i().unpack(str[start:end])
      self.stampA.canon()
      self.stampB.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4I4f2i().pack(_x.stampA.secs, _x.stampA.nsecs, _x.stampB.secs, _x.stampB.nsecs, _x.a0, _x.a1, _x.a2, _x.a3, _x.lane_mark_type, _x.lane_mark_quality))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.stampA is None:
        self.stampA = genpy.Time()
      if self.stampB is None:
        self.stampB = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.stampA.secs, _x.stampA.nsecs, _x.stampB.secs, _x.stampB.nsecs, _x.a0, _x.a1, _x.a2, _x.a3, _x.lane_mark_type, _x.lane_mark_quality,) = _get_struct_4I4f2i().unpack(str[start:end])
      self.stampA.canon()
      self.stampB.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4I4f2i = None
def _get_struct_4I4f2i():
    global _struct_4I4f2i
    if _struct_4I4f2i is None:
        _struct_4I4f2i = struct.Struct("<4I4f2i")
    return _struct_4I4f2i
