(cl:in-package genesis_path_follower-msg)
(cl:export '(HEADER-VAL
          HEADER
          SOLVE_STATUS-VAL
          SOLVE_STATUS
          SOLVE_TIME-VAL
          SOLVE_TIME
          XS-VAL
          XS
          YS-VAL
          YS
          VS-VAL
          VS
          PSIS-VAL
          PSIS
          XR-VAL
          XR
          YR-VAL
          YR
          VR-VAL
          VR
          PSIR-VAL
          PSIR
          DF-VAL
          DF
          ACC-VAL
          ACC
          SS-VAL
          SS
          EYS-VAL
          EYS
          EPSIS-VAL
          EPSIS
          CRF-VAL
          CRF
          VRF-VAL
          VRF
))