(cl:in-package genesis_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          INDEX-VAL
          INDEX
          ALIVE_COUNT_A-VAL
          ALIVE_COUNT_A
          OBJECT_IDENTIFIER-VAL
          OBJECT_IDENTIFIER
          OBJECT_AGE-VAL
          OBJECT_AGE
          OBJECT_VALID-VAL
          OBJECT_VALID
          OBJECT_MODE-VAL
          OBJECT_MODE
          OBJECT_LANE-VAL
          OBJECT_LANE
          ANGLE_RATE-VAL
          ANGLE_RATE
          ANGLE_LEFT-VAL
          ANGLE_LEFT
          ANGLE_RIGHT-VAL
          ANGLE_RIGHT
          CIPV-VAL
          CIPV
          BRAKE_LIGHTS-VAL
          BRAKE_LIGHTS
          BLINKER_INFO-VAL
          BLINKER_INFO
          ALIVE_COUNT_B-VAL
          ALIVE_COUNT_B
          RANGE-VAL
          RANGE
          RANGE_RATE-VAL
          RANGE_RATE
          MOTION_STATUS-VAL
          MOTION_STATUS
          ACCEL_X-VAL
          ACCEL_X
          POSITION_Y-VAL
          POSITION_Y
))