(cl:defpackage posedetection_msgs-srv
  (:use )
  (:export
   "DETECT"
   "<DETECT-REQUEST>"
   "DETECT-REQUEST"
   "<DETECT-RESPONSE>"
   "DETECT-RESPONSE"
   "FEATURE0DDETECT"
   "<FEATURE0DDETECT-REQUEST>"
   "FEATURE0DDETECT-REQUEST"
   "<FEATURE0DDETECT-RESPONSE>"
   "FEATURE0DDETECT-RESPONSE"
   "FEATURE1DDETECT"
   "<FEATURE1DDETECT-REQUEST>"
   "FEATURE1DDETECT-REQUEST"
   "<FEATURE1DDETECT-RESPONSE>"
   "FEATURE1DDETECT-RESPONSE"
   "TARGETOBJ"
   "<TARGETOBJ-REQUEST>"
   "TARGETOBJ-REQUEST"
   "<TARGETOBJ-RESPONSE>"
   "TARGETOBJ-RESPONSE"
  ))

